### ISSUE TITLE
What are channels?

### ISSUE THREAD

**Issue by joshuamabina** [vanilophp/channel#1]
Hi there,

Looking at the documentation, I couldn't seem to find the answers to:

- what is `channel`?
- what are it's possible use cases?

With a little guidance, i'm happy to help with the documentation.

Really appreciate.

**Comment by fulopattila122** [comment]
In today's E-commerce the shop site is no longer the only point of sale.
Channels represent a single sales channel, which can be one of the following things:
- Webstore
- Mobile application
- Cashier in your physical store
- Facebook integration,
- ...

or pretty much anything similar you can imagine.

This feature in Vanilo is quite unfinished yet. It needs to be integrated with orders/checkout in order to be fully functional.

Typically you can define per channel:
- different set of available products
- different currencies and/or prices
- available language(s)

In the end, each of your orders should be aware of which channel has it been placed.
